config/routes.rb
Rails.application.routes.draw do
  
  resources :drivers do
    resources :driver_statements 
  end
  resources :customers
  resources :trips do
    resources :trip_transactions
  end
  root to: 'pages#home' 

  
get 'driver_trips/:id', to: 'drivers#trips'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/driver_statement.rb
class DriverStatement < ApplicationRecord
  belongs_to :driver

  has_many :statementtripizations
  has_many :trips, through: :statementtripizations
  accepts_nested_attributes_for :trips
end

app/controllers/driver_statements_controller.rb
class DriverStatementsController < ApplicationController
  before_action :get_driver
  before_action :set_driver_statement, only: [:show, :edit, :update, :destroy]


  # GET /driver_statements
  # GET /driver_statements.json
  def index
    @driver_statements = @driver.driver_statements
  end

  # GET /driver_statements/1
  # GET /driver_statements/1.json
  def show 
  end

  # GET /driver_statements/new
  def new
    # trip.driver_statements.ids 
    @driver_trips = @driver.trips
    driver_statements = @driver.driver_statements

    @driver_statement = @driver.driver_statements.build
    @completed_trips = @driver.trips.where(["status = ?", "Completed"])
    
    # @completed_trips =
    # if @driver.driver_statements.exists?(params[:id])
    #   @completed_trips = @driver.trips.where(["status = ?", "Completed"])
    # end

  end

  # GET /driver_statements/1/edit
  def edit
    @completed_trips = @driver.trips.where(["status = ?", "Completed"]).order(:id)
  end

  # POST /driver_statements
  # POST /driver_statements.json
  def create

    @driver_statement = @driver.driver_statements.build(driver_statement_params)
    # shark_posts_path(@shark)
    respond_to do |format|
      if @driver_statement.save
        format.html { redirect_to driver_driver_statement_path(@driver, @driver_statement), notice: 'Driver statement was successfully created.' }
        format.json { render :show, status: :created, location: @driver_statement }
      else
        format.html { render :new }
        format.json { render json: @driver_statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /driver_statements/1
  # PATCH/PUT /driver_statements/1.json
  def update
    respond_to do |format|
      if @driver_statement.update(driver_statement_params)
        format.html { redirect_to driver_driver_statement_path(@driver), notice: 'Driver statement was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver_statement }
      else
        format.html { render :edit }
        format.json { render json: @driver_statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /driver_statements/1
  # DELETE /driver_statements/1.json
  def destroy

    @driver_statement.destroy
    respond_to do |format|
      format.html { redirect_to driver_driver_statements_path(@driver), notice: 'Driver statement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_driver
      @driver = Driver.find(params[:driver_id])
    end
 

    def set_driver_statement
      @driver_statement = @driver.driver_statements.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_statement_params
      params.require(:driver_statement).permit(:driver_id, :due_date, :paid, { :trip_ids => [] })
    end
end

app/helpers/driver_statements_helper.rb
module DriverStatementsHelper
end

app/views/driver_statements/_form.html.erb
<%= simple_form_for [@driver, driver_statement] do |f| %>


  <div class="form-inputs">
  <% f.collection_select :driver_id, Driver.order(:last_name),:id,:driver_full_name, include_blank: true %> 

    <%= f.input :due_date %>
    <% if controller_name == 'driver_statements' && action_name == 'edit' %>
    <%= f.input :paid %>
    <% end %>
    <%= f.collection_check_boxes(:trip_ids, @completed_trips, :id, :id) %>
  </div>
<table class="table table-striped">
  <thead>
    <tr>
    <th scope="col">Trip</th>
      <th scope="col">Distance</th>
      <th scope="col">Gross</th>
      <th scope="col">driver_statement?</th>
      <th scope="col">Customer</th>
    </tr>
  </thead>

  <tbody>

    <% @completed_trips.each do |trip| %>
    <tr>
      <th><%= link_to trip.id, trip_path(trip) %></th>
      <th><%= trip.distance %></th>
      <td><%= number_to_currency(trip.amount) %></td>
      <td>
      <%= trip.driver_statements.ids %>

      </td>
      <td>##</td>
    </tr>
    
<% end %>

  </tbody>
  
</table>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/driver_statements/edit.html.erb
<h1>Editing Driver Statement</h1>

<%= render 'form', driver_statement: @driver_statement %>

<%= link_to 'Show', [@driver, @driver_statement] %> |
<%= link_to 'Back', driver_driver_statements_path(@driver) %>

app/views/driver_statements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Driver Statements</h1>

<table>
  <thead>
    <tr>
      <th>Driver</th>
      <th>Due date</th>
      <th>Paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @driver_statements.each do |driver_statement| %>
      <tr>
        <td><%= driver_statement.driver.driver_full_name %></td>
        <td><%= driver_statement.due_date %></td>
        <td><%= driver_statement.paid %></td>
        <td><%= link_to 'Show', driver_driver_statement_path(driver_statement.driver, driver_statement)  %></td>
        <td><%= link_to 'Edit', edit_driver_driver_statement_path(driver_statement.driver, driver_statement) %></td>
        <td><%= link_to 'Destroy', [@driver, driver_statement], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver Statement', new_driver_driver_statement_path(@driver) %>

app/views/driver_statements/new.html.erb
<h1>New Driver Statement</h1>

<%= render 'form', driver_statement: @driver_statement %>



<%= link_to 'Back', driver_driver_statements_path(@driver) %>

app/views/driver_statements/show.html.erb
<% total_distance = 0 %>

<p>
  <strong>Driver:</strong>
  <%= @driver_statement.driver.driver_full_name %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @driver_statement.due_date %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @driver_statement.paid %>
</p>
<table class="table table-striped">
  <thead>
    <tr>
    <th scope="col">Trip</th>
      <th scope="col">Distance</th>
      <th scope="col">Driver rate</th>
      <th scope="col">Driver</th>
      <th scope="col">Customer</th>
    </tr>
  </thead>

  <tbody>

    <% @driver_statement.trips.each do |trip| %>
    <tr>
      <th><%= link_to trip.id, trip_path(trip) %></th>
      <th><%= trip.distance %></th>
      <td><%= number_to_currency(trip.driver_rate) %></td>
      <td>##</td>
      <td>##</td>
    </tr>

    <%= total_distance = total_distance + trip.distance %>
<% end %>

  </tbody>
  
</table>
<%= link_to 'Edit', edit_driver_driver_statement_path(@driver, @driver_statement) %> |
<%= link_to 'Back', driver_driver_statements_path %>


 <br /> 
    <table class="table table-bordered table-striped table-condensed table-responsive">
      <thead>
        <tr>
          <th>Total Miles</th>

        </tr>
      </thead>
      <%  %>
      <tbody>
        <tr>
          <td><%= total_distance %></td>

        </tr>
      </tbody>
    </table>