config/routes.rb
Rails.application.routes.draw do
  
  resources :drivers do
    resources :driver_statements 
  end
  resources :customers
  resources :trips do
    resources :trip_transactions
  end
  root to: 'pages#home' 

  
get 'driver_trips/:id', to: 'drivers#trips'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/trip_transactions_controller.rb
class TripTransactionsController < ApplicationController

    
  def create
    @trip = Trip.find(params[:trip_id])
    @trip_transaction = @trip.trip_transactions.create(trip_transaction_params)
    # @trip_transaction.user_id = current_user.id if current_user
    # @user = current_user
    if @trip_transaction.save
      # CommentMailer.new_trip_transaction(@trip_transaction).deliver_later
      flash[:success] = "The trip_transaction has been saved."
      redirect_to trip_path(@trip)
    else
      redirect_to trip_path(@trip)
      flash[:danger] = "#{}, We have these errors: " + @trip_transaction.errors.full_messages.to_sentence 
    end
  end 

  def update
    @trip = Trip.find(params[:trip_id])
    @trip_transaction = @trip.trip_transactions.find(params[:id])
    # is_not_trip_transaction_owner
    if @trip_transaction.update(trip_transaction_params)
      flash[:success] = "The trip_transaction has been updated."
      redirect_to trip_path(@trip)
    else 
      flash[:danger] = "#{@trip_transaction.user.first_name}, We have these errors: " + @trip_transaction.errors.full_messages.to_sentence 
      redirect_back(fallback_location: root_path)
  end 
end

  def edit
    @trip = Trip.find(params[:trip_id])
    @trip_transaction = @trip.trip_transactions.find(params[:id])
    # is_not_trip_transaction_owner
  end 
  
  def destroy
    @trip = Trip.find(params[:trip_id])
    @trip_transaction = @trip.trip_transactions.find(params[:id]) 
    if 
      @trip_transaction.destroy
      flash[:warning] = "The trip_transaction has been deleted."
      redirect_to trip_path(@trip)
    else
      flash[:danger] = "You do not own this trip_transaction!"
      redirect_back(fallback_location: root_path)
    end
  end
  

private

  # def is_not_trip_transaction_owner
  #   if current_user != @trip_transaction.user 
  #     flash[:danger] = "You do not own this trip_transaction!"
  #     redirect_back(fallback_location: root_path)
  #   end
  # end 

  def trip_transaction_params
    params.require(:trip_transaction).permit(:address, :pick_up, :drop_off, :order, :trip_id, :amount)
  end

end

app/views/trip_transactions/_form.html.erb
<%= simple_form_for [@trip, @trip.trip_transactions.build] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :amount %>
    <%= f.input :description, label: "Description" %>


  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trip_transactions/_trip_transaction.html.erb
<%= trip_transaction.description %>

<%= number_to_currency(trip_transaction.amount) %>
<%= link_to 'Edit Transaction', edit_trip_trip_transaction_path(trip_transaction.trip, trip_transaction), class: 'btn btn-outline-info btn-sm' %> 
<%= link_to 'Delete', [trip_transaction.trip, trip_transaction], method: :delete, data: {confirm: "This can't be undone!" }, class: 'btn btn-danger btn-sm'%>

app/views/trip_transactions/edit.html.erb
<h1>Editing Pick Drop</h1>
<%= bootstrap_flash %> 
<%= simple_form_for [@trip, @trip_transaction] do |f| %>

<%= f.input :address %>
<%= f.submit "Update" %> 
<% end %>

app/views/trip_transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pick Drops</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Pick up</th>
      <th>Drop off</th>
      <th>Order</th>
      <th>Trip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trip_transactions.each do |trip_transaction| %>
      <tr>
        <td><%= trip_transaction.address %></td>
        <td><%= trip_transaction.pick_up %></td>
        <td><%= trip_transaction.drop_off %></td>
        <td><%= trip_transaction.order %></td>
        <td><%= trip_transaction.trip %></td>
        <td><%= link_to 'Show', trip_transaction %></td>
        <td><%= link_to 'Edit', edit_trip_transaction_path(trip_transaction) %></td>
        <td><%= link_to 'Destroy', trip_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pick Drop', new_trip_transaction_path %>

app/views/trip_transactions/new.html.erb
<h1>New Pick Drop</h1>

<%= render 'form', trip_transaction: @trip_transaction %>

<%= link_to 'Back', trip_transactions_path %>

app/views/trip_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>description:</strong>
  <%= @trip_transaction.description %>
</p>

<p>
  <strong>amount:</strong>
  <%= @trip_transaction.amount %>
</p>



<%= link_to 'Edit', edit_trip_transaction_path(@trip_transaction) %> |
<%= link_to 'Back', trip_transactions_path %>