config/routes.rb
Rails.application.routes.draw do
  
  resources :drivers do
    resources :driver_statements 
  end
  resources :customers
  resources :trips do
    resources :trip_transactions
  end
  root to: 'pages#home' 

  
get 'driver_trips/:id', to: 'drivers#trips'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/driver.rb
class Driver < ApplicationRecord

  has_many :trips
  has_many :driver_statements
  # validates_numericality_of :rate, greater_than_or_equal_to: 0.05, less_than_or_equal_to: 0.99, :message => "Driver Rate needs to be between 0.05 and 0.99" 



  def driver_full_name
    return self.first_name + " " + self.last_name
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy, :driver_trips]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        flash[:danger] = @driver.errors.full_messages.to_sentence
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        flash[:danger] = @driver.errors.full_messages.to_sentence
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def driver_trips
  end 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:first_name, :last_name, :dob, :hire_date, :truck_id, :rate) 
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= simple_form_for(@driver) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
 

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.number_field :rate, :step => "0.01", min: '0.05', max: '0.99'  %>  


    <%= f.input :dob %>
    <%= f.input :hire_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Dob</th>
      <th>Hire date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.first_name %></td>
        <td><%= driver.last_name %></td>
        <td><%= driver.dob %></td>
        <td><%= driver.hire_date %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @driver.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @driver.last_name %>
</p>

<p>
  <strong>Driver Rate:</strong>
  <%= number_to_currency(@driver.rate) %>
</p>
<p>
  <strong>Dob:</strong>
  <%= @driver.dob %>
</p>

<p>
  <strong>Hire date:</strong>
  <%= @driver.hire_date %>
</p>

<p>
 
  <%= link_to "Create Driver Statement", new_driver_driver_statement_path(@driver) %> 
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>


<table class="table table-striped">
  <thead>
    <tr>
    <th scope="col">Trip</th>
      <th scope="col">Distance</th>
      <th scope="col">Gross</th>
      <th scope="col">Driver</th>
      <th scope="col">Customer</th>
    </tr>
  </thead>

  <tbody>

    <% @driver.trips.each do |driver| %>
    <tr>
      <th><%= link_to driver.id, trip_path(driver) %></th>
      <th><%= driver.distance %></th>
      <td><%= number_to_currency(driver.amount) %></td>
      <td>##</td>
      <td>##</td>
    </tr>
<% end %>

  </tbody>
  
</table>